### ISSUE TITLE
Deploying the Chocolatey package for 3.71.0 failed

### ISSUE THREAD

**Issue by justinvp** [pulumi/pulumi-chocolatey#13]
https://github.com/pulumi/pulumi-chocolatey/actions/runs/5246209600/jobs/9475744140#step:3:37

```
Run $version = "3.71.0"
Chocolatey v2.0.0
'.', hexadecimal value 0x00, is an invalid character. Line 2, position 1.
Chocolatey v2.0.0
No .nupkg files (or more than 1) were found to build in 'D:\a\pulumi-chocolatey\pulumi-chocolatey\pulumi'. Please specify the .nupkg file or try in a different directory.
```

The previous deployment of 3.70.0 [succeeded](https://github.com/pulumi/pulumi-chocolatey/actions/runs/5215569224/jobs/9413260267).

The difference? The 3.70.0 job used Chocolatey `v1.4.0` whereas the most recent one that failed is using Chocolatey `v2.0.0`.

**Comment by justinvp** [comment]
I'm not sure if this is a Chocolatey bug or if there's a null character in one of our files that the new version of Chocolatey can't handle. Apparently, `System.Xml` will throw an exception when reading XML and it encounters a null character. Is it trying to read a file that is encoded with Unicode rather than UTF-8?

@Frassle, any ideas?

**Comment by Frassle** [comment]
The nuspec was UTF16 encoded, old versions of choco must have mangled through with that somehow.
I'll check other files and push a fix.

**Comment by Frassle** [comment]
Hmm not so simple, fresh checkout now says its already UTF8 but I saw the same 0x0 error running locally to start.

**Comment by Frassle** [comment]
Looks like it's the script that rewrites the files to add the version numbers is also changing their encoding. Adding a `-Encoding utf8` flag to them seems to help.
