### ISSUE TITLE
Pulumi fails validation in Chocolatey after switching to pulumi-watch

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-chocolatey#6]
See https://community.chocolatey.org/packages/pulumi/3.39.0

> pulumi has failed automated validation.
>
> Requirements
>
> Requirements represent the minimum quality of a package that is acceptable. When a package version has failed requirements, the package version requires fixing and/or response by the maintainer. Provided a Requirement has flagged correctly, it must be fixed before the package version can be approved. The exact same version should be uploaded during moderation review.
>
>    Package automation scripts download a remote file without validating the checksum. [More...](https://docs.chocolatey.org/en-us/community-repository/moderation/package-validator/rules/cpmr0073)
>
> Notes
>
> Notes typically flag things for both you and the reviewer to go over. Sometimes this is the use of things that may or may not be necessary given the constraints of what you are trying to do and/or are harder for automation to flag for other reasons. Items found in Notes might be Requirements depending on the context. A package version can be approved without addressing Note comments.
>
>    Binary files (.exe, .msi, .zip) have been included. The reviewer will ensure the maintainers have distribution rights. [More...](https://docs.chocolatey.org/en-us/community-repository/moderation/package-validator/rules/cpmr0060)

I suspect this is due to https://github.com/pulumi/pulumi/pull/10213

**Comment by mikhailshilkov** [comment]
Ah, apparently this is new on the Chocolatey side, so maybe my diagnose is wrong: https://blog.chocolatey.org/2022/08/upcoming-changes-validator/

**Comment by TheCakeIsNaOH** [comment]
Looking at this package, it is using `Install-ChocolateyZipPackage`, which is intended for downloading and extracting archives that are located at a remote URI. However, the package actually embeds the archive inside the package file (`.nupkg`), in which case `Get-ChocolateyUnzip` is the better helper function to use. 

The requirement for having a checksum is based on usage of `Install-ChocolateyZipPackage`, so if that is not used, that validation rule will not trip.

https://docs.chocolatey.org/en-us/create/functions/get-chocolateyunzip

**Comment by AaronFriel** [comment]
There shouldn't be a `.nupkg` in our release artifacts. I think @mikhailshilkov might be right, based on the "notes". It appears 3.39.1 was able to publish OK, should we close this?

**Comment by iwahbe** [comment]
Since https://community.chocolatey.org/packages/pulumi/3.39.1 shows as published successfully, I think we can close.

**Comment by mikhailshilkov** [comment]
@iwahbe Not really, see https://twitter.com/gep13/status/1566881109497024512

> We ran into some issues with the new rule after deploying it, so we have temporarily turn it off, but it will be going back on.

**Comment by iwahbe** [comment]
@mikhailshilkov Thanks for pointing me to the problem. I'll get into it.
